services:
  - type: web
    name: melotoons-title-generator
    runtime: docker
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
